ALTER TABLE file_servers ADD COLUMN retain_hourly INTEGER NOT NULL DEFAULT 24;
ALTER TABLE file_servers ADD COLUMN retain_daily INTEGER NOT NULL DEFAULT 7;
ALTER TABLE file_servers ADD COLUMN retain_weekly INTEGER NOT NULL DEFAULT 4;
ALTER TABLE file_servers ADD COLUMN retain_yearly INTEGER NOT NULL DEFAULT 1;
ALTER TABLE file_servers ADD COLUMN schedule_start TEXT NOT NULL DEFAULT '';

ALTER TABLE databases ADD COLUMN retain_hourly INTEGER NOT NULL DEFAULT 24;
ALTER TABLE databases ADD COLUMN retain_daily INTEGER NOT NULL DEFAULT 7;
ALTER TABLE databases ADD COLUMN retain_weekly INTEGER NOT NULL DEFAULT 4;
ALTER TABLE databases ADD COLUMN retain_yearly INTEGER NOT NULL DEFAULT 1;
ALTER TABLE databases ADD COLUMN schedule_start TEXT NOT NULL DEFAULT '';
